[package]
name = "mymypy"
version = "0.1.0"
authors = ["Masaki.F"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1.0"
regex = "0.1"
term = "0.4.6"
difference = "2.0"